name: Docker Actions

on:
  workflow_dispatch

jobs:
  action:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrete.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrete.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - uses: actions/checkout@v2

      - name: validate
        uses: ./.github/actions/validate
