name: My Terraform Actions

on:
  workflow_dispatch

jobs:
  action:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - uses: actions/checkout@v2

      - name: validate
        uses: ./.github/actions/validate

      - name: plan
        uses: ./.github/actions/plan
