name: Docker Actions

on:
  workflow_dispatch

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: validate
        uses: ./.github/actions/validate