name: My Terraform Actions

on:
  workflow_dispatch

jobs:
  action:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2

      - name: validate
        uses: ./.github/actions/validate

      - name: plan
        uses: ./.github/actions/plan
